# -------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight SCA build
    branches:
      include:
        - master

trigger:
  - none

pr:
  branches:
    include:
      - master

variables:
  - group: asgardeo-common-secrets

pool: 'asgardeo-shared-scale-set-agents'

resources:
  repositories:
    - repository: templates
      type: github
      name: wso2-enterprise/azure-pipeline-templates
      ref: refs/heads/main
      endpoint: asgardeo-github-sca-scan

jobs:
  - job: sca_scan
    displayName: SCA scan
    steps:
      - powershell: |
          $branchName = "$(Build.SourceBranch)".Replace("refs/heads/", "")
          Write-Host "##vso[task.setvariable variable=simpleBranchName]$branchName"
        displayName: 'Extract branch name'
      - template: ci-pipelines/templates/sca-scan-jfrog.yaml@templates
        parameters:
          PROJECT_TYPE: mvn
          GITHUB_CONNECTION: asgardeo-github-sca-scan
          ACCESS_TOKEN: $(JFROG-ACCESS-TOKEN) # JFrog access token
      - template: ci-pipelines/templates/sca-scan.yaml@templates
        parameters:
          API_KEY: $(FOSSA-API-KEY)
          BRANCH: $(simpleBranchName)
          REPO_NAME: 'asgardeo-java-oidc-sdk'
          GITHUB_ORG: 'asgardeo'
